#!/bin/sh
# build image
docker image rm -f gorvel-img
docker build -t gorvel-img .

# build container
docker container rm -f gorvel-container
docker run -d -p 8333:8080 -p 8334:8081 --name gorvel-container gorvel-img
