#!/bin/sh
docker pull daison12006013/lucid
docker container rm -f lucid-container
# | detach
# | ports        [host -> guest]:
#     lucid     [8330 -> 8080]
#     sveltekit  [8331 -> 8081]
# | container name to "lucid-container" from daison12006013/lucid image
# | mount current folder to container's /app folder
docker run -v $(PWD):/app -d -p 8330:8080 -p 8331:8081 --name lucid-container daison12006013/lucid

# re-build again after mounting the folder to sync the files
docker exec -it lucid-container sh -c "sh ./cmd/install-reflex.sh && exit"
docker exec -it lucid-container sh -c "sh ./cmd/check-binaries.sh && exit"
docker exec -it lucid-container sh -c "sh ./cmd/build-go.sh && exit"
docker exec -it lucid-container sh -c "sh ./cmd/build-svelte.sh && exit"
