#!/bin/sh
docker pull daison12006013/gorvel
docker container rm -f gorvel-container
# | detach
# | ports        [host -> guest]:
#     gorvel     [8330 -> 8080]
#     sveltekit  [8331 -> 8081]
# | container name to "gorvel-container" from daison12006013/gorvel image
# | mount current folder to container's /app folder
docker run -v $(PWD):/app -d -p 8330:8080 -p 8331:8081 --name gorvel-container daison12006013/gorvel

# re-build again after mounting the folder to sync the files
docker exec -it gorvel-container sh -c "sh ./cmd/install-reflex.sh && exit"
docker exec -it gorvel-container sh -c "sh ./cmd/check-binaries.sh && exit"
docker exec -it gorvel-container sh -c "sh ./cmd/build-go.sh && exit"
docker exec -it gorvel-container sh -c "sh ./cmd/build-svelte.sh && exit"
